apiVersion: v1
kind: PersistentVolume
metadata:
  name: alysio-dm-wordpress-pv
  namespace: alysio-dm
  labels:
    app: wordpress
    tier: frontend
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/alysio-dm-wordpress
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alysio-dm-mysql-pv
  namespace: alysio-dm
  labels:
    app: wordpress
    tier: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/alysio-dm-mysql