apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alysio-dm-wordpress-pvc
  namespace: alysio-dm
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alysio-dm-mysql-pvc
  namespace: alysio-dm
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi