apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: alysio-dm
spec:
  selector:
    matchLabels:
      app: wordpress-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: password
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: password
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: user
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: database
          ports:
            - containerPort: 3306
              name: wordpress-mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-persistent-storage
---
apiVersion: v1
kind: Service
metadata:
  namespace: alysio-dm
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: wordpress-mysql