apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-php-config
  namespace: alysio-dm
data:
  uploads.ini: |-
    file_uploads = On
    upload_max_filesize = 500M
    post_max_size = 500M
    memory_limit = 400M
    max_execution_time = 600
